name: luthor
description: A Dart validation library inspired by zod
version: 0.0.1+1
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor
homepage: https://github.com/exaby73/luthor/tree/main/packages/luthor

environment:
  sdk: '>=2.19.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.21.0
