name: luthor_generator
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/exaby73/band/tree/main/packages/band

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  luthor_annotation: any

dependency_overrides:
  luthor_annotation:
    path: ../luthor_annotation

dev_dependencies:
  lint: ^2.0.1
  test: ^1.21.0
