name: luthor_generator
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/exaby73/band/tree/main/packages/band

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  analyzer: ^5.10.0
  build: ^2.3.1
  collection: ^1.17.1
  luthor_annotation: any
  source_gen: ^1.2.7

dependency_overrides:
  luthor_annotation:
    path: ../luthor_annotation

dev_dependencies:
  lint: ^2.0.1
  test: ^1.21.0
